import logging
from pathlib import Path
import pytest
import os

import neat_ml.workflow.lib_workflow as wf


def test_get_path_structure_builds_expected_paths(tmp_path: Path):
    """
    get_path_structure: builds proc_dir and det_dir using ds_id/method/class/time_label.
    """
    roots = {"work": str(tmp_path)}
    ds = {"id": "DS1", "method": "OpenCV", "class": "pos", "time_label": "T01"}

    paths = wf.get_path_structure(roots, ds)

    base = tmp_path / "DS1" / "OpenCV" / "pos" / "T01"
    assert paths["proc_dir"] == base / "T01_Processed_OpenCV"
    assert paths["det_dir"] == base / "T01_Processed_OpenCV_With_Blob_Data"


def test_get_path_structure_missing_work_raises_keyerror(tmp_path: Path):
    """
    If 'work' key is missing in roots, a KeyError is raised.
    """
    roots = {"result": str(tmp_path)}
    ds = {"id": "DS1", "method": "OpenCV", "class": "pos", "time_label": "T01"}

    with pytest.raises(KeyError, match="work"):
        wf.get_path_structure(roots, ds)

def test_stage_opencv_warns_when_paths_missing(caplog: pytest.LogCaptureFixture, tmp_path: Path):
    """
    stage_opencv: if 'det_dir' (or 'proc_dir') missing -> warning and return.
    """
    caplog.set_level(logging.WARNING)
    ds = {"id": "DS3", "method": "OpenCV", "detection": {"img_dir": str(tmp_path)}}
    paths = {"proc_dir": tmp_path / "p"}  # det_dir missing

    wf.stage_opencv(ds, paths)

    assert "Detection paths not built (step not selected or misconfig). Skipping." in caplog.text


def test_stage_opencv_warns_when_img_dir_missing(caplog: pytest.LogCaptureFixture, tmp_path: Path):
    """
    stage_opencv: if detection.img_dir missing -> warning and return.
    """
    caplog.set_level(logging.WARNING)
    ds = {"id": "DS4", "method": "OpenCV", "detection": {}}
    paths = {"proc_dir": tmp_path / "p", "det_dir": tmp_path / "d"}

    wf.stage_opencv(ds, paths)

    assert "No 'detection.img_dir' set for dataset 'DS4'. Skipping detection." in caplog.text


def test_stage_opencv_skips_if_output_already_exists(
    caplog: pytest.LogCaptureFixture, 
    tmp_path: Path, 
):
    """
    stage_opencv: if *_bubble_data.parquet.gzip exists -> skip and DO NOT call pipeline steps.
    """
    caplog.set_level(logging.INFO)

    proc_dir = tmp_path / "proc"
    det_dir = tmp_path / "det"
    det_dir.mkdir(parents=True)
    (det_dir / "anything_bubble_data.parquet.gzip").write_text("done")

    ds = {"id": "DS5", "method": "OpenCV", "detection": {"img_dir": str(tmp_path)}}
    paths = {"proc_dir": proc_dir, "det_dir": det_dir}

    wf.stage_opencv(ds, paths)

    assert "Detection already exists for DS5. Skipping." in caplog.text


def test_stage_opencv_pipeline_runs(
    tmp_path: Path, 
    caplog: pytest.LogCaptureFixture, 
):
    """
    stage_opencv: test that ``stage_opencv``
    runs successfully when provided the appropriate
    directories.
    """
    caplog.set_level(logging.INFO)
    proc_dir = tmp_path / "proc"
    det_dir = tmp_path / "det"
    img_dir = tmp_path / "imgs"
    img_dir.mkdir()

    ds = {
        "id": "DS6", 
        "method": "OpenCV", 
        "detection": {
            "img_dir": str(img_dir), 
            "debug": True
        }
    }
    paths = {"proc_dir": proc_dir, "det_dir": det_dir}

    wf.stage_opencv(ds, paths)
    
    # assert that all the correct ``logging`` outputs were generated,
    # signifying that the corresponding processes were run, and assert
    # that the appropriate directories were generated
    assert "Preprocessing (OpenCV) for" in caplog.text
    assert "Detecting (OpenCV) for" in caplog.text
    assert "OpenCV Detection Ran Successfully." in caplog.text 
    assert proc_dir.exists() and not os.listdir(proc_dir)
    assert det_dir.exists() and (os.listdir(det_dir) == 
        ['.joblib_cache'])


def test_stage_detect_routes_to_opencv(
    tmp_path: Path
):
    """
    stage_detect: method 'OpenCV' routes to stage_opencv.
    """
    ds = {
        "id": "DS7",
        "method": "OpenCV",
        "detection": {
            "img_dir": tmp_path / "i"
        }
    }
    paths = {
        "proc_dir": tmp_path / "p",
        "det_dir": tmp_path / "d",
    }
    exp_columns = {
        "image_filepath",
        "num_blobs_opencv",
        "median_radii_opencv"
    }
    df_out = wf.stage_detect(ds, paths)
    # assert that an empty dataframe was generated by 
    # calling the ``stage_opencv`` function
    assert df_out is not None
    assert df_out.empty
    assert exp_columns.issubset(df_out.columns)


def test_stage_detect_unknown_method_error(
    tmp_path: Path
):
    """
    stage_detect: unknown method -> ValueError.
    """
    ds = {"id": "DS8", "method": "SomethingElse"}
    paths = {"proc_dir": tmp_path / "p", "det_dir": tmp_path / "d"}
    
    with pytest.raises(ValueError, match="Unknown detection method"):
        wf.stage_detect(ds, paths)
