image: python:3.12.1

before_script:
  - python --version
  - python -m venv venv
  - source venv/bin/activate
  - python -m pip install -U mypy ruff pandas-stubs matplotlib xgboost

stages:
  - lint

lint:
  stage: lint
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
  allow_failure: false
  script:
    - mypy .
    - ruff check .
