image: python:3.12.1

before_script:
  - python --version
  - python -m venv venv
  - source venv/bin/activate
  - python -m pip install -U mypy ruff pandas-stubs matplotlib xgboost pandas scikit-learn openpyxl jinja2 python-ternary pytest shap interpret types-tqdm types-Pillow scikit-image

stages:
  - lint
  - test

lint:
  stage: lint
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
  allow_failure: false
  script:
    - mypy .
    - ruff check .

# a crude end-to-end test of the entire workflow
functional_test:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
  allow_failure: false
  script:
    - python main.py

unit_tests:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
  allow_failure: false
  script:
    - python -m pip install -v .
    - cd /tmp && python -m pytest --pyargs neat_ml
